const StorySeeder =
        [{
            "profile_photo": "http://dummyimage.com/238x100.png/cc0000/ffffff",
            "user_name": "Chaim"
          }, {
            "profile_photo": "http://dummyimage.com/101x100.png/5fa2dd/ffffff",
            "user_name": "Kerwin"
          }, {
            "profile_photo": "http://dummyimage.com/196x100.png/ff4444/ffffff",
            "user_name": "Lisbeth"
          }, {
            "profile_photo": "http://dummyimage.com/177x100.png/dddddd/000000",
            "user_name": "Izzy"
          }, {
            "profile_photo": "http://dummyimage.com/151x100.png/ff4444/ffffff",
            "user_name": "Garvey"
          }, {
            "profile_photo": "http://dummyimage.com/109x100.png/cc0000/ffffff",
            "user_name": "Pierette"
          }, {
            "profile_photo": "http://dummyimage.com/141x100.png/5fa2dd/ffffff",
            "user_name": "Raina"
          }, {
            "profile_photo": "http://dummyimage.com/210x100.png/5fa2dd/ffffff",
            "user_name": "Almira"
          }, {
            "profile_photo": "http://dummyimage.com/138x100.png/5fa2dd/ffffff",
            "user_name": "Diane"
          }, {
            "profile_photo": "http://dummyimage.com/211x100.png/5fa2dd/ffffff",
            "user_name": "Marnie"
          }, {
            "profile_photo": "http://dummyimage.com/161x100.png/dddddd/000000",
            "user_name": "Laurence"
          }, {
            "profile_photo": "http://dummyimage.com/109x100.png/cc0000/ffffff",
            "user_name": "Catie"
          }, {
            "profile_photo": "http://dummyimage.com/184x100.png/cc0000/ffffff",
            "user_name": "Clint"
          }, {
            "profile_photo": "http://dummyimage.com/165x100.png/5fa2dd/ffffff",
            "user_name": "Retha"
          }, {
            "profile_photo": "http://dummyimage.com/125x100.png/ff4444/ffffff",
            "user_name": "Zea"
          }, {
            "profile_photo": "http://dummyimage.com/158x100.png/5fa2dd/ffffff",
            "user_name": "Rosalia"
          }, {
            "profile_photo": "http://dummyimage.com/145x100.png/5fa2dd/ffffff",
            "user_name": "Giavani"
          }, {
            "profile_photo": "http://dummyimage.com/108x100.png/5fa2dd/ffffff",
            "user_name": "Brittani"
          }, {
            "profile_photo": "http://dummyimage.com/161x100.png/ff4444/ffffff",
            "user_name": "Shaina"
          }, {
            "profile_photo": "http://dummyimage.com/148x100.png/ff4444/ffffff",
            "user_name": "Matthiew"
          }, {
            "profile_photo": "http://dummyimage.com/160x100.png/cc0000/ffffff",
            "user_name": "Dorise"
          }, {
            "profile_photo": "http://dummyimage.com/145x100.png/cc0000/ffffff",
            "user_name": "Juanita"
          }, {
            "profile_photo": "http://dummyimage.com/180x100.png/cc0000/ffffff",
            "user_name": "Quinlan"
          }, {
            "profile_photo": "http://dummyimage.com/242x100.png/cc0000/ffffff",
            "user_name": "Kean"
          }, {
            "profile_photo": "http://dummyimage.com/149x100.png/dddddd/000000",
            "user_name": "Katrinka"
          }, {
            "profile_photo": "http://dummyimage.com/187x100.png/5fa2dd/ffffff",
            "user_name": "Thorndike"
          }, {
            "profile_photo": "http://dummyimage.com/104x100.png/5fa2dd/ffffff",
            "user_name": "Sabrina"
          }, {
            "profile_photo": "http://dummyimage.com/167x100.png/5fa2dd/ffffff",
            "user_name": "Willette"
          }, {
            "profile_photo": "http://dummyimage.com/234x100.png/5fa2dd/ffffff",
            "user_name": "Aryn"
          }, {
            "profile_photo": "http://dummyimage.com/147x100.png/5fa2dd/ffffff",
            "user_name": "Darrin"
          }, {
            "profile_photo": "http://dummyimage.com/234x100.png/cc0000/ffffff",
            "user_name": "Lindsey"
          }, {
            "profile_photo": "http://dummyimage.com/154x100.png/cc0000/ffffff",
            "user_name": "Merridie"
          }, {
            "profile_photo": "http://dummyimage.com/219x100.png/cc0000/ffffff",
            "user_name": "Katine"
          }, {
            "profile_photo": "http://dummyimage.com/197x100.png/cc0000/ffffff",
            "user_name": "Kort"
          }, {
            "profile_photo": "http://dummyimage.com/133x100.png/dddddd/000000",
            "user_name": "Evangelia"
          }, {
            "profile_photo": "http://dummyimage.com/154x100.png/ff4444/ffffff",
            "user_name": "Madeleine"
          }, {
            "profile_photo": "http://dummyimage.com/162x100.png/dddddd/000000",
            "user_name": "Lester"
          }, {
            "profile_photo": "http://dummyimage.com/122x100.png/cc0000/ffffff",
            "user_name": "Herby"
          }, {
            "profile_photo": "http://dummyimage.com/227x100.png/cc0000/ffffff",
            "user_name": "Franchot"
          }, {
            "profile_photo": "http://dummyimage.com/211x100.png/cc0000/ffffff",
            "user_name": "Clement"
          }, {
            "profile_photo": "http://dummyimage.com/205x100.png/5fa2dd/ffffff",
            "user_name": "Tades"
          }, {
            "profile_photo": "http://dummyimage.com/189x100.png/cc0000/ffffff",
            "user_name": "Evelyn"
          }, {
            "profile_photo": "http://dummyimage.com/211x100.png/ff4444/ffffff",
            "user_name": "Josey"
          }, {
            "profile_photo": "http://dummyimage.com/171x100.png/dddddd/000000",
            "user_name": "Cris"
          }, {
            "profile_photo": "http://dummyimage.com/234x100.png/dddddd/000000",
            "user_name": "Katya"
          }, {
            "profile_photo": "http://dummyimage.com/228x100.png/5fa2dd/ffffff",
            "user_name": "Eb"
          }, {
            "profile_photo": "http://dummyimage.com/203x100.png/cc0000/ffffff",
            "user_name": "Urbanus"
          }, {
            "profile_photo": "http://dummyimage.com/187x100.png/ff4444/ffffff",
            "user_name": "Julian"
          }, {
            "profile_photo": "http://dummyimage.com/160x100.png/5fa2dd/ffffff",
            "user_name": "Job"
          }, {
            "profile_photo": "http://dummyimage.com/166x100.png/5fa2dd/ffffff",
            "user_name": "Madelina"
          }, {
            "profile_photo": "http://dummyimage.com/131x100.png/5fa2dd/ffffff",
            "user_name": "Margaux"
          }, {
            "profile_photo": "http://dummyimage.com/247x100.png/ff4444/ffffff",
            "user_name": "Weylin"
          }, {
            "profile_photo": "http://dummyimage.com/137x100.png/dddddd/000000",
            "user_name": "Melessa"
          }, {
            "profile_photo": "http://dummyimage.com/168x100.png/ff4444/ffffff",
            "user_name": "Carroll"
          }, {
            "profile_photo": "http://dummyimage.com/113x100.png/5fa2dd/ffffff",
            "user_name": "Isabelita"
          }, {
            "profile_photo": "http://dummyimage.com/190x100.png/dddddd/000000",
            "user_name": "Rebecca"
          }, {
            "profile_photo": "http://dummyimage.com/239x100.png/ff4444/ffffff",
            "user_name": "Celestyna"
          }, {
            "profile_photo": "http://dummyimage.com/102x100.png/5fa2dd/ffffff",
            "user_name": "Gayla"
          }, {
            "profile_photo": "http://dummyimage.com/212x100.png/ff4444/ffffff",
            "user_name": "Catrina"
          }, {
            "profile_photo": "http://dummyimage.com/223x100.png/5fa2dd/ffffff",
            "user_name": "Brewster"
          }, {
            "profile_photo": "http://dummyimage.com/211x100.png/dddddd/000000",
            "user_name": "Carson"
          }, {
            "profile_photo": "http://dummyimage.com/130x100.png/5fa2dd/ffffff",
            "user_name": "Erica"
          }, {
            "profile_photo": "http://dummyimage.com/188x100.png/5fa2dd/ffffff",
            "user_name": "Michele"
          }, {
            "profile_photo": "http://dummyimage.com/249x100.png/5fa2dd/ffffff",
            "user_name": "Nert"
          }, {
            "profile_photo": "http://dummyimage.com/206x100.png/dddddd/000000",
            "user_name": "Doro"
          }, {
            "profile_photo": "http://dummyimage.com/232x100.png/ff4444/ffffff",
            "user_name": "Annis"
          }, {
            "profile_photo": "http://dummyimage.com/142x100.png/cc0000/ffffff",
            "user_name": "Ray"
          }, {
            "profile_photo": "http://dummyimage.com/112x100.png/5fa2dd/ffffff",
            "user_name": "Kasey"
          }, {
            "profile_photo": "http://dummyimage.com/222x100.png/5fa2dd/ffffff",
            "user_name": "Zandra"
          }, {
            "profile_photo": "http://dummyimage.com/223x100.png/5fa2dd/ffffff",
            "user_name": "Farra"
          }, {
            "profile_photo": "http://dummyimage.com/129x100.png/ff4444/ffffff",
            "user_name": "Milissent"
          }, {
            "profile_photo": "http://dummyimage.com/120x100.png/cc0000/ffffff",
            "user_name": "Veriee"
          }, {
            "profile_photo": "http://dummyimage.com/140x100.png/ff4444/ffffff",
            "user_name": "Gibbie"
          }, {
            "profile_photo": "http://dummyimage.com/107x100.png/ff4444/ffffff",
            "user_name": "Issi"
          }, {
            "profile_photo": "http://dummyimage.com/156x100.png/ff4444/ffffff",
            "user_name": "Orsa"
          }, {
            "profile_photo": "http://dummyimage.com/168x100.png/cc0000/ffffff",
            "user_name": "Gratia"
          }, {
            "profile_photo": "http://dummyimage.com/190x100.png/ff4444/ffffff",
            "user_name": "Heddi"
          }, {
            "profile_photo": "http://dummyimage.com/218x100.png/cc0000/ffffff",
            "user_name": "Jonah"
          }, {
            "profile_photo": "http://dummyimage.com/222x100.png/dddddd/000000",
            "user_name": "Meier"
          }, {
            "profile_photo": "http://dummyimage.com/229x100.png/ff4444/ffffff",
            "user_name": "Rayshell"
          }, {
            "profile_photo": "http://dummyimage.com/114x100.png/ff4444/ffffff",
            "user_name": "Suzy"
          }, {
            "profile_photo": "http://dummyimage.com/233x100.png/dddddd/000000",
            "user_name": "Sheffield"
          }, {
            "profile_photo": "http://dummyimage.com/243x100.png/ff4444/ffffff",
            "user_name": "Jameson"
          }, {
            "profile_photo": "http://dummyimage.com/103x100.png/5fa2dd/ffffff",
            "user_name": "Meredithe"
          }, {
            "profile_photo": "http://dummyimage.com/108x100.png/cc0000/ffffff",
            "user_name": "Nariko"
          }, {
            "profile_photo": "http://dummyimage.com/154x100.png/ff4444/ffffff",
            "user_name": "Ricky"
          }, {
            "profile_photo": "http://dummyimage.com/235x100.png/5fa2dd/ffffff",
            "user_name": "Mord"
          }, {
            "profile_photo": "http://dummyimage.com/187x100.png/cc0000/ffffff",
            "user_name": "Sybil"
          }, {
            "profile_photo": "http://dummyimage.com/167x100.png/cc0000/ffffff",
            "user_name": "Andie"
          }, {
            "profile_photo": "http://dummyimage.com/180x100.png/ff4444/ffffff",
            "user_name": "Fallon"
          }, {
            "profile_photo": "http://dummyimage.com/221x100.png/dddddd/000000",
            "user_name": "Lari"
          }, {
            "profile_photo": "http://dummyimage.com/104x100.png/ff4444/ffffff",
            "user_name": "Curry"
          }, {
            "profile_photo": "http://dummyimage.com/249x100.png/ff4444/ffffff",
            "user_name": "Obie"
          }, {
            "profile_photo": "http://dummyimage.com/122x100.png/cc0000/ffffff",
            "user_name": "Darryl"
          }, {
            "profile_photo": "http://dummyimage.com/221x100.png/ff4444/ffffff",
            "user_name": "Gris"
          }, {
            "profile_photo": "http://dummyimage.com/171x100.png/cc0000/ffffff",
            "user_name": "Kristal"
          }, {
            "profile_photo": "http://dummyimage.com/228x100.png/5fa2dd/ffffff",
            "user_name": "Thorsten"
          }, {
            "profile_photo": "http://dummyimage.com/162x100.png/5fa2dd/ffffff",
            "user_name": "Isidoro"
          }, {
            "profile_photo": "http://dummyimage.com/154x100.png/5fa2dd/ffffff",
            "user_name": "Kingsley"
          }, {
            "profile_photo": "http://dummyimage.com/128x100.png/cc0000/ffffff",
            "user_name": "Ibrahim"
          }]

module.exports = StorySeeder;